services:
  app:
    build: .
    container_name: presence_app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "file:/app/prisma/dev.db"
    command: ["npm", "run", "dev"]
